--1.Using set operations, find the employee ID’s of those employees who are not working on any projects.
SELECT EMP_ID FROM EMPLOYEES 
MINUS
SELECT E.EMP_ID FROM EMPLOYEES E
INNER JOIN WORKON W
ON E.EMP_ID = W.EMP_ID;

--2.Using set operations and sub-query, find the names of those employees who are not working on any projects.
SELECT EMP_NAME FROM EMPLOYEES
MINUS
SELECT EMP_NAME
FROM EMPLOYEES E
WHERE EXISTS(SELECT PROJECT_NUMBER
                  FROM WORKON W
                  WHERE W.EMP_ID = E.EMP_ID);

--3.Using set operations, find the names of employees who work on both the Eagle and Super Jet projects.
SELECT EMP_NAME FROM EMPLOYEES
INTERSECT
SELECT E.EMP_NAME FROM EMPLOYEES E
LEFT JOIN WORKON W
ON E.EMP_ID=W.EMP_ID
LEFT JOIN PROJECTS P
ON W.PROJECT_NUMBER = P.PROJECT_NUMBER
WHERE P.PROJECT_NAME IN ('EAGLE', 'SUPER JET')
HAVING COUNT(DISTINCT W.PROJECT_NUMBER) = 2
GROUP BY E.EMP_NAME;

--4.Using set operations, find the names of employees who work on either the Eagle or the Super Jet projects.
SELECT EMP_NAME FROM EMPLOYEES
INTERSECT
SELECT E.EMP_NAME FROM EMPLOYEES E
LEFT JOIN WORKON W
ON E.EMP_ID=W.EMP_ID
LEFT JOIN PROJECTS P
ON W.PROJECT_NUMBER = P.PROJECT_NUMBER
WHERE P.PROJECT_NAME IN ('EAGLE', 'SUPER JET')
HAVING COUNT(DISTINCT W.PROJECT_NUMBER) =1
GROUP BY E.EMP_NAME;

--5.Using non-correlated sub-query, find the names of employees who work on both the Eagle and Super Jet projects.
SELECT E.EMP_NAME FROM EMPLOYEES E 
WHERE E.EMP_ID IN (SELECT W.EMP_ID FROM WORKON W
LEFT JOIN PROJECTS P
ON W.PROJECT_NUMBER = P.PROJECT_NUMBER
WHERE P.PROJECT_NAME IN ('EAGLE', 'SUPER JET')
HAVING COUNT(DISTINCT W.PROJECT_NUMBER) = 2
GROUP BY W.EMP_ID);

--6.Using correlated sub-query, find the names of employees who work on both the Eagle and Super Jet projects.
SELECT E.EMP_NAME FROM EMPLOYEES E 
WHERE EXISTS(SELECT W.EMP_ID FROM WORKON W
WHERE W.EMP_ID = E.EMP_ID
HAVING COUNT(DISTINCT W.PROJECT_NUMBER) = 2
GROUP BY W.EMP_ID);

--7.Using sub-query, find the names of employees who work on both the Eagle and Super Jet projects and have a rate greater or equal to 80.
SELECT EMP_NAME
FROM EMPLOYEES E, RATE R
WHERE E.RATE_CATEGORY = R.RATE_CATEGORY
AND RATE IN 
(SELECT RATE
FROM EMPLOYEES E, RATE R
WHERE E.RATE_CATEGORY = R.RATE_CATEGORY
AND R.RATE>=80);

------------ALTERNATIVE SOLUTION-------------
SELECT EM.EMP_NAME FROM EMPLOYEES EM
INNER JOIN RATE R
ON EM.RATE_CATEGORY = R.RATE_CATEGORY
INNER JOIN(
SELECT E.EMP_NAME FROM WORKON W 
LEFT JOIN PROJECTS P
ON W.PROJECT_NUMBER = P.PROJECT_NUMBER
LEFT JOIN EMPLOYEES E
ON W.EMP_ID=E.EMP_ID
WHERE P.PROJECT_NAME IN ('EAGLE', 'SUPER JET')
HAVING COUNT(DISTINCT W.PROJECT_NUMBER) = 2
GROUP BY E.EMP_NAME) F
ON EM.EMP_NAME=F.EMP_NAME
WHERE R.RATE>=80;



